
<div class="currency-value-list">
    <p> USD : <b><?php echo $block->getRate('USD'); ?></b><small> Toman</small></p>
    <p> TRY : <b><?php echo $block->getRate('TRY'); ?></b><small> Toman</small></p>
    <p> EUR : <b><?php echo $block->getRate('EUR'); ?></b><small> Toman</small></p>
    <p> EAD : <b><?php echo $block->getRate('AED'); ?></b><small> Toman</small></p>
</div>

<form class="currency-input-list" action="" method="post">
    <label for="usd">USD</label>
    <input type="text" name="usd" value="<?php echo $block->getRate('USD'); ?>">
    <label for="try">TRY</label>
    <input type="text" name="try" value="<?php echo $block->getRate('TRY'); ?>">
    <label for="eur">EUR</label>
    <input type="text" name="eur" value="<?php echo $block->getRate('EUR'); ?>">
    <label for="aed">AED</label>
    <input type="text" name="aed" value="<?php echo $block->getRate('AED'); ?>">
    <button type="submit">Update</button>
</form>

<?php
/* TODO:
    - Read log file and create table
*/
?>



<style>
    .currency-value-list{
        padding: 10px;
        background: #e5e5e5;
        margin-bottom: 40px;
    }
    .currency-value-list p{
        display: inline-block;
        padding: 0 30px;
        border-right: 1px #a1a1a1 solid;
    }
    .currency-input-list input{
        margin-right: 20px;
    }
</style>
