<?php
/* TODO:
    - Create Input for currency (same as configuration)
    - Fill inputs by value of configuration. Use function that would defined in block (for instance $block->myFunction() )
*/
?>
<div class="currency-value-list">
    <p> USD : <b><?php echo $block->getRate('USD'); ?></b><small> Toman</small></p></b>
    <p> TRY : <b><?php echo $block->getRate('TRY'); ?></b><small> Toman</small></p></b>
    <p> EUR : <b><?php echo $block->getRate('EUR'); ?></b><small> Toman</small></p></b>
    <p> EAD : <b><?php echo $block->getRate('AED'); ?></b><small> Toman</small></p></b>
</div>
<div>
    <label for="usd">USD</label>
    <input type="text" name="usd" value="<?php echo $block->getRate('USD'); ?>">
    <label for="try">TRY</label>
    <input type="text" name="try" value="<?php echo $block->getRate('TRY'); ?>">
    <label for="eur">EUR</label>
    <input type="text" name="eur" value="<?php echo $block->getRate('EUR'); ?>">
    <label for="aed">AED</label>
    <input type="text" name="aed" value="<?php echo $block->getRate('AED'); ?>">
</div>

<style>
    .currency-value-list{
        padding: 10px;
        background: #e5e5e5;
        margin-bottom: 40px;
    }
    .currency-value-list p{
        display: inline-block;
        padding: 0px 30px;
        border-right: 1px #a1a1a1 solid;
    }
</style>
